### ISSUE TITLE
Display Set can have CIV without value

### ISSUE THREAD

**Issue by miriam-groeneveld** [comic/grand-challenge.org#3087] opened 2023-11-10 13:03 UTC
**Describe the bug**

**To Reproduce**
1. Go to https://grand-challenge.org/reader-studies/cirruscoreweb-release-default-answers/ 
2. Click on `Cases`, then `View/Delete Cases` 
3. Expand the first display set. Note that there is no value for the interface `regions-of-interest`:
![image](https://github.com/comic/grand-challenge.org/assets/51329283/9dd6d49b-63ed-4d79-856a-72078c59ffe3)
4. Click on `Edit Case`
5. Dropdown for `regions-of-interest` shows empty entries
![image](https://github.com/comic/grand-challenge.org/assets/51329283/b800a054-9c7c-49e5-892a-8f31309c346d)
6. Selecting the `---` option and save has no effect (should be a differnt bug maybe?)
7. Click on `View Display Set`
8. Cirrus will show error:
![image](https://github.com/comic/grand-challenge.org/assets/51329283/f227762c-140a-4cfa-b322-6f12002f227f)

The empty dropdown list issue can be reproduced by editing the Display Set and selecting an existing json file for the text-report interface, see video:

https://github.com/comic/grand-challenge.org/assets/51329283/a629f56c-83f0-44fd-925a-46a05f28f986

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by amickan** [comment] 2023-11-13 09:23
I found out why the regions of interest file gets deleted when you add a text report file, but still not entirely sure how the empty CIVs got created in the first place. Could it be that the regions-of-interest interface used to be stored in the DB? There is a second issue in the DS update view where updating a json interface stored in the DB results in empty CIVs being created, so that could explain it.

**Comment by amickan** [comment] 2023-11-13 09:41
Knowing of this issue, there are probably more empty CIVs in the database (specifically of json interfaces stored in the db or those that used to be stored in the db). Could you check if that's true, James?

**Comment by jmsmkn** [comment] 2023-11-13 10:26
> Could it be that the regions-of-interest interface used to be stored in the DB?

No, it is not possible to change the storage type directly. When we do we run a management command. These were definitely created with the storage set correctly.

> Knowing of this issue, there are probably more empty CIVs in the database (specifically of json interfaces stored in the db or those that used to be stored in the db). Could you check if that's true, James?

There are, but this is not coming from changing of storage type and happens regardless of how the interface is defined. There are even images that are empty where the storage type is not relevant.

**Comment by amickan** [comment] 2023-11-13 14:14
I made a PR that addresses some of the issues with the display set updating, but I can't figure out what caused the CIVs for the regions-of-interest interface to be empty. I worked my way through the entire DS updating/creating codebase and tried things locally and all seems to work as expected for files and images (see fixed for json values in the PR)... 

How "old" are those CIVs? Maybe the issues was fixed in an earlier PR already?

**Comment by miriam-groeneveld** [comment] 2023-11-13 14:42
The default reader study that shows the issue is part of the release checklist, so the problem wasn't there yet on October 13th, the latest release date.

**Comment by amickan** [comment] 2023-11-13 14:44
With issue you mean that the empty CIVs were not there then, you mean? Or the issue that updating one of the files, deletes the other file? Or both?

**Comment by pkcakeout** [comment] 2023-11-13 14:46
Could be a red Herring though: I noticed that the workstation from 13 October also did not throw any error for some reason when encountering the None-value on the file...

**Comment by amickan** [comment] 2023-11-13 15:25
From the pks of the empty CIVs, it looks like they were created a while ago, so could be that there was an issue back then that has been fixed in the meantime, but I can't immediately find a PR that changed something that would account for this, so I'm probably overlooking something somewhere.

**Comment by miriam-groeneveld** [comment] 2023-11-13 15:26
> With issue you mean that the empty CIVs were not there then, you mean? Or the issue that updating one of the files, deletes the other file? Or both?

Yes, the empty CIV's were still proper CIV's at that time. I think I added some new questions after that, to do some other tests, which probably led to the empty civ's. 

> Could be a red Herring though: I noticed that the workstation from 13 October also did not throw any error for some reason when encountering the None-value on the file...

Well, the release checklist specifically asks if there are 7 accept/reject options, so then the CIV had content.

**Comment by miriam-groeneveld** [comment] 2023-11-13 15:28
> From the pks of the empty CIVs, it looks like they were created a while ago, so could be that there was an issue back then that has been fixed in the meantime, but I can't immediately find a PR that changed something that would account for this, so I'm probably overlooking something somewhere.

But you can reproduce the issue in a new displayset right? First add a regions-of-interest, save, add a text-reort.json, regions-of-interest is empty.

**Comment by pkcakeout** [comment] 2023-11-13 16:05
> Well, the release checklist specifically asks if there are 7 accept/reject options, so then the CIV had content.

Ok, sorry, convinced!

**Comment by amickan** [comment] 2023-11-15 07:56
> Yes, the empty CIV's were still proper CIV's at that time. I think I added some new questions after that, to do some other tests, which probably led to the empty civ's.

Hm, strange.. A CIV can't be changed after creation. We normally create a new CIV when the value changes and remove the old civ from the display set and attach the new one instead. So I assumed that something went wrong with updating the CIV, a file failing validation or something along those lines, but I can't reproduce updating issues locally with files at least - when validation fails, we properly roll back the CIV creation. 

> But you can reproduce the issue in a new displayset right? First add a regions-of-interest, save, add a text-report.json, regions-of-interest is empty.

Yes, I can reproduce that, but this issue is seperate from the empty CIV issue. There is a bug that when you add a text-report (or any file for that matter), any previously attached json file civ (in this case the regions-of-interest json) gets deleted - but deleting here means that the entire CIV gets removed from the display set, not the content from the CIV.

**Comment by miriam-groeneveld** [comment] 2023-11-16 06:50
Ah, well, in that case, I have no idea how we got there. Is it something that could have been done in the django admin?

**Closed** 2023-11-23 09:01 UTC
