### ISSUE TITLE
Option for editing reader study answers 

### ISSUE THREAD

**Issue by Whardian** [comic/grand-challenge.org#1071] opened 2020-01-08 09:40 UTC
I am currently using the reader study software of grand-challenge, but it appears that I cannot correct my answers (sometimes I made a mistake). It would be great to navigate to previously scored images and edit your response. Could this functionality be added to grand-challenge?

**Comment by jmsmkn** [comment] 2020-01-08 11:31
Duplicate of #1013

**Closed by jmsmkn** 2020-01-08 11:31 UTC
