### ISSUE TITLE
"This field is required" error when uploading a DICOM file

### ISSUE THREAD

**Issue by njmhendrix** [comic/grand-challenge.org#1888] opened 2021-06-29 15:37 UTC
**Describe the bug**
My co-promotor tried to upload an original DICOM file (hand x-ray) from the Jeroen Bosch Hospital to Grand Challenge for trying out my scaphoid fracture detection algorithm, but somehow he still received the “this field is required” error message and was unable to complete the submission (see screenshot; he did not click on "Submit" directly without selecting a file). 

**To Reproduce**
Contact me if you need the DICOM file for analysis. I expect that the error can be reproduced by selecting this file for submission on the "Try-out Algorithm" page.

**Screenshots**
![grand_challenge_screenshot](https://user-images.githubusercontent.com/47858231/123824758-9b13f000-d8fe-11eb-9c60-aea55eb59804.png)

**Desktop:**
 - OS: Windows 10
 - Browser: Internet Explorer

**Comment by jmsmkn** [comment] 2021-06-29 19:39
Duplicate of https://github.com/comic/grand-challenge.org/issues/1489#issuecomment-681627693

**Closed by jmsmkn** 2021-06-29 19:39 UTC

**Comment by njmhendrix** [comment] 2021-06-30 11:10
Thanks for your quick response James, I would like to add that I have further investigated this issue with my co-promotor and it appears that the model never confirms the upload (printing "Uploaded: [filename]") when using Internet Explorer. When using Google Chrome, the upload is immediately confirmed as soon as the progress bar is full. I will add a disclaimer to my algorithm page that users must visit https://grand-challenge.org/ using a recent internet browser.

**Comment by jmsmkn** [comment] 2021-06-30 14:27
You shouldn't need to add a warning. Internet Explorer went end of life in 2015, it's worrying that some people are still using it (3% of gc users!). Microsoft recommends using Edge with the built in "Internet Explorer Mode" if it is needed for legacy sites.

**Comment by njmhendrix** [comment] 2021-06-30 14:53
Okay, I expected this group of GC users to be somewhat larger, thanks for the info! Apparently, Internet Explorer is still configured as the default internet browser on some of the radiology workstations at the Jeroen Bosch Hospital, perhaps I can contact the IT department to fix this.
