### ISSUE TITLE
Unclear when uploading for a DisplaySet fails

### ISSUE THREAD

**Issue by chrisvanrun** [comic/grand-challenge.org#3042] opened 2023-09-22 12:04 UTC
# Description
* Click "Add Case (single)"
* Provide files for all the interfaces
* Hit the save button

# Expected:
The status of the upload(s) is visible somewhere

# What actually happens:
You are presented with an empty display set (none) with no idea what is going on:

![image](https://github.com/comic/grand-challenge.org/assets/7871310/352b1421-2e67-4b1d-9339-d314da726b34)

**Comment by chrisvanrun** [comment] 2023-09-22 12:05
A quick solution would be to redirect to the uploads after creating a case and add a link to the Uploads lists.

**Comment by chrisvanrun** [comment] 2023-09-22 15:04
With some patience this is generally okay, but if one of the uploads fails it becomes nigh impossible for a regular user to figure out what is going on (apart from asking us).

**Comment by amickan** [comment] 2023-11-01 13:43
The user does get some feedback. At the top of the screen, it says: "Display set created. Image and file import jobs have been queued."  The message box can be easily overlooked, I guess, but this is how we show error messages or info messages everywhere else on the website as well. We could add a link to the uploads page in the message. Not sure if I like redirecting to the uploads page. I always find it a bit irritating if I get redirected away from the page I was on.

**Comment by pkcakeout** [comment] 2023-11-01 14:23
I actually think the form is quite bugged, now that I had to use it recently. Check this for example:

![image](https://github.com/comic/grand-challenge.org/assets/11632379/9ecbf8bc-4566-478b-9dee-68c08c3a06b5)

> Please correct the errors below.

I assume that means that some errors should be highlighted? I am quite sure I saw some explanatory text in the past. What was wrong here is that the `Prostate-cancer-risk-score` had to be changed to "High". Also, there is a second issue with the "text report". On the next page you see:

![image](https://github.com/comic/grand-challenge.org/assets/11632379/549ce93c-0e83-49eb-8af3-9a88a1c504e0)

... ok so I go to the file uploads `https://grand-challenge.org/cases/uploads/` and see:

![image](https://github.com/comic/grand-challenge.org/assets/11632379/36e2fc5b-f0e9-4a3b-b2d7-8cb64770b22d)

No errors, nothing that I am aware of, but then looking at the display-set, the `text-report` key is still missing:

![image](https://github.com/comic/grand-challenge.org/assets/11632379/2b28547d-528d-40d8-ad35-fdb815f0a359)

Reason for this is that no `.txt` file was expected, and the text-report had to be a valid `.json` structure!

**Comment by jmsmkn** [comment] 2023-11-01 18:20
I think this needs a larger section of work as Archive Items are a mess too and have the same problems. Conceptually they are basically the same thing so could be unified.

**Comment by chrisvanrun** [comment] 2024-01-08 09:56
Not sure if it's on the scope, but uploading an invalid JSON (not schema per se, but incorrectly formatted JSON) just fails silently.

**Comment by amickan** [comment] 2024-01-12 14:22
> Not sure if it's on the scope, but uploading an invalid JSON (not schema per se, but incorrectly formatted JSON) just fails silently.

I think this is an issue with our JsonEditor. The error message is there, it's just hidden until you click on the little x at the bottom right of the editor window. Or was this different for you?

**Comment by pkcakeout** [comment] 2024-01-12 15:49
Hey Anne!

If you parse my wall-of-text from https://github.com/comic/grand-challenge.org/issues/3042#issuecomment-1789048605 you will find a series of screenshots that describe what Chris also tries to describe, I think. The problem is that some CIs require that you upload a _file_. This file just gets silently rejected after the upload with no error message being shown. So there is no JSON-editor in the mix... unless you already changed something and my whole post is outdated.

**Comment by amickan** [comment] 2024-01-15 07:31
Thanks Paul. There are several issues here. What you describe (and possibly what Chris describes as well) is because the validation happens asynchronously, so immediate feedback is not possible. Users get a notification when the validation fails in those cases, but that is silent, too, so not very user friendly. The only thing I can think of would be to say this explicitly in the confirmation message that appears at the top of the page with a link to the notifications page for reference. Would that help you think? or do you have any other suggestions?

**Comment by pkcakeout** [comment] 2024-01-15 09:26
> or do you have any other suggestions?

The async import is what I suspected as well. I think from a pure user-perspective it would make _most sense_ if there was a "import page" for each submitted archive item/display set and one could see the state (success/failed/in progress...) there. I totally understand that this might be a lot of work though.

At the bare minimum, getting _some_ feedback and a link to where to find it for imported json structures would be sufficient, because they do not even appear in the "uploads" section, so I have no clue where to find those errors...

**Comment by chrisvanrun** [comment] 2024-01-15 14:00
Just my 2 cents. I would expect it to have shown up in the uploads list as a failed upload attempt. Because it wasn't there I had not  a clue what went wrong until I pulled up Sentry.

**Comment by pkcakeout** [comment] 2024-01-15 17:11
@chrisvanrun  I ultimately found out that you can see the errors here as well:

![image](https://github.com/comic/grand-challenge.org/assets/11632379/6d39e17f-bcc4-4bb1-9069-5eb0820368aa)

And then:

![image](https://github.com/comic/grand-challenge.org/assets/11632379/00cf385a-b8ce-4390-8466-db2a37677029)

**Comment by chrisvanrun** [comment] 2024-01-16 14:27
That only shows when it is:
- Valid JSON
- Doesn't adhere to a JSON schema

If you try to upload invalid JSON, it is 'muisstil'.

**Comment by pkcakeout** [comment] 2024-01-17 10:04
Hey Chris... ah okay, that is very much possible, good point. I did not check this situation again and just assumed that those errors also appear here! @amickan  - maybe there is an answer already. Have the "not valid json" error appear _at least_ in the notifications then?

**Comment by amickan** [comment] 2024-01-17 10:21
> If you try to upload invalid JSON, it is 'muisstil'.

Really? I can't seem to be able to replicate that. I still get a notification for invalid json. Can you share an example of a file you tried this with? Or do you mean that if you enter invalid json in the json editor (i.e. not a file upload interface)?

**Comment by pkcakeout** [comment] 2024-01-17 11:23
Hmm... answer lies somewhere in between, I guess:

![image](https://github.com/comic/grand-challenge.org/assets/11632379/694111d3-7eb3-4e2f-b87a-5949c443a32d)

This appears after uploading the file "nojson.txt" with contents

~~~~~
Really no json in here at all!
~~~~~

This is "no valid json"... the error message seems very unclear though. It is clearer if the json does not fit the required format. But  they for sure appear, indeed! So sorry for the incorrect report. The message could be a bit clearer though that this is a JSON-parser error ("No valid json")... and of course it would be very welcome if the error could actually appear on or after the upload-page...

**Comment by amickan** [comment] 2024-01-17 11:54
Ok, yes, the message is a bit cryptic. Not sure why that is, it's what json.loads() returns when passing it the file contents. I'll investigate. 

As for having the errors show up on the upload page: the upload page is limited to image uploads. Those are different Django objects and we shouldn't mix them with the file upload objects. We could add a seperate page that tracks file uploads, but they get deleted once a day, so there would be limited use to such a page I think. In any case, implementing such a view is out of scope for this pitch, but I can create a new issue if we think this is necessary. 

What I suggest we do instead (for now at least), is inform users that they will be notified about errors related to file uploads (both files and images) in their notifications. We can do that by adding a link to their notifications in the success message like so:

![image](https://github.com/comic/grand-challenge.org/assets/30069334/b0efaaec-acd8-4cb6-b7eb-0739d05e216d)

Would that work in your eyes?

**Comment by pkcakeout** [comment] 2024-01-17 11:55
I think that will work, yes!

**Comment by chrisvanrun** [comment] 2024-01-18 13:21
Now that I think about it a bit more. I observed that error when helping someone in person (Lena) with uploading an annotation via the regular interface. And I never thought of looking at the notifications at the time.

I quickly reproduced the scenario and can confirm a notification will be created. I didn't even **know** GC _had_ notifications. 🙃

**Closed** 2024-01-18 13:29 UTC
