### ISSUE TITLE
Option to make leaderboards and submissions visible to only registered participants

### ISSUE THREAD

**Issue by prash-p** [comic/grand-challenge.org#1461] opened 2020-08-12 13:35 UTC
**Is your feature request related to a problem? Please describe.**
I'm running a number of private challenges amongst some colleagues, where the data, algorithms, etc are not yet ready to be published. So all the pages on the challenge page are privately accessible to only those users whose registration has been aproved. However the leaderboard page and submitted evaluation jobs seem to be visible to anyone who has the URL, even if the evaluation job is not marked to be visible on the leaderboard. (e.g. www.example.grand-challenge.org/evaluation/submissions/evaluationID would be visible even to someone who hasn't registered to the challenge)

**Describe the solution you'd like**
Give admins the option to make the leaderboard and submissions visible only to participants who have registered and been approved

**Comment by jmsmkn** [comment] 2020-08-12 13:49
Duplicate of https://github.com/comic/grand-challenge.org/issues/682

**Closed by jmsmkn** 2020-08-12 13:49 UTC
