### ISSUE TITLE
Colour JPG support for reader studies

### ISSUE THREAD

**Issue by Whardian** [comic/grand-challenge.org#1058] opened 2019-12-19 09:07 UTC
For my PhD project, I created a reader study on grand-challenge. A jpg/png importer has been added (#1046), but it appears that my colour jpg images are converted to black-and-white when I open the reader study. Is it possible to support colour jpg images? Many thanks in advance.

**Comment by jmsmkn** [comment] 2019-12-19 09:52
Duplicate of https://github.com/DIAGNijmegen/rse-cirrus-core/issues/278

**Closed by jmsmkn** 2019-12-19 09:52 UTC
