### ISSUE TITLE
Inform user of financial consequences of GPU and memory changes.

### ISSUE THREAD

**Issue by miriam-groeneveld** [comic/grand-challenge.org#3692] opened 2024-11-11 09:35 UTC
**Is your feature request related to a problem? Please describe.**
Changing algorithm settings such as GPU and memory have implications for costs, but the user is not informed about this.

**Describe the solution you'd like**
Add some details in the help text of the relevant settings that inform the algorithm owner that changing these settings has financial consequences (and therefor the number of credits required)

**Describe alternatives you've considered**
This should be descibed in the documentation as well.

**Additional context**
Lot's of algorithm owners request more resources than what they use, but they are not made aware that that actually costs us money.

**Comment by jmsmkn** [comment] 2024-11-12 09:35
Duplicate of https://github.com/DIAGNijmegen/rse-grand-challenge-admin/issues/326

**Closed by jmsmkn** 2024-11-12 09:35 UTC
