### ISSUE TITLE
Failed image imports do not show details

### ISSUE THREAD

**Issue by miriam-groeneveld** [comic/grand-challenge.org#3266] opened 2024-02-29 07:37 UTC
**Describe the bug**
As reported by a user. Try out an algorithm with an uploaded image. The image upload fails but shows no details:

![Screenshot 2024-02-26 at 11 41 03 AM](https://github.com/comic/grand-challenge.org/assets/51329283/b7aa2547-03ec-43a6-b48d-643219bee5fc)

Sentry report: https://grand-challenge.sentry.io/issues/4997160349/?project=303639&query=&referrer=issue-stream&statsPeriod=7d&stream_index=17

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**

**Additional context**

**Comment by chrisvanrun** [comment] 2024-02-29 08:22
More detailed duplicate of the following?
https://github.com/comic/grand-challenge.org/issues/3139

**Comment by jmsmkn** [comment] 2024-02-29 08:54
Duplicate of https://github.com/DIAGNijmegen/rse-grand-challenge-admin/issues/136

**Closed by jmsmkn** 2024-02-29 08:54 UTC
