### ISSUE TITLE
remove or edit a question

### ISSUE THREAD

**Issue by aswolinskiy** [comic/grand-challenge.org#1312] opened 2020-04-20 13:52 UTC
It is currently not possible to remove or edit a question (all fields are gray).
Some changes should be easy to make, e.g. the question text or a change from required to non-required. Other changes will require more work, but intermediately a warning should suffice that already given answers will be deleted if the question changes. (Such changes will probably made before the ready really starts anyway)

**Comment by jmsmkn** [comment] 2020-04-20 14:01
Questions are not editable once an answer has been created for them as it's possible to change the meaning of the question after it is answered. Only the fields that do no influence this are then editable at that point. The rest is a duplicate of #1111

**Closed by jmsmkn** 2020-04-20 14:01 UTC
