### ISSUE TITLE
Stuck on launching a reader study

### ISSUE THREAD

**Issue by njmhendrix** [comic/grand-challenge.org#989] opened 2019-11-12 12:42 UTC
**Describe the bug**
When launching a reader study, users can get stuck at the "starting reader study" screen (see screenshot below). 

**To Reproduce**
Launch any reader study. 

**Screenshots**
 ![image-20191109-084800](https://user-images.githubusercontent.com/47858231/68656179-9f28a980-0531-11ea-8f41-db392b57db86.png)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome

**Additional context**
One of my readers reported this problem when launching a reader study containing full sized x-rays converted into mha files. Refreshing the webpage did not solve the problem.

**Comment by jmsmkn** [comment] 2019-11-12 12:51
I cannot reproduce this on Chrome, for CIRRUS Core or the CXR Workstation. It's probably specific to your data, can you add the user `jamesmeakin.diag` to the list of users?

**Comment by njmhendrix** [comment] 2019-11-12 13:09
Thanks for your quick reply, I just added your account to the list of readers.

**Comment by jmsmkn** [comment] 2019-11-12 13:12
I still cannot reproduce this. Do you get the same behaviour in a guest window (top right of chrome, open guest window)?

**Comment by njmhendrix** [comment] 2019-11-12 13:22
I submitted this issue on behalf of someone else, I also cannot reproduce this behavior on my own system. I will send you a private message with more information.

**Comment by jmsmkn** [comment] 2019-11-12 14:08
Closing as this cannot be reproduced.

**Closed by jmsmkn** 2019-11-12 14:08 UTC
